### ISSUE TITLE
Add map detection to FieldDescriptorProto for JavaScript

### ISSUE THREAD

**Issue by tatethurston** [protocolbuffers/protobuf-javascript#13]
**What language does this apply to?**
JavaScript code generation.

**Describe the problem you are trying to solve.**

Presently there is no way to determine whether a given field is a message type or a [map](https://developers.google.com/protocol-buffers/docs/proto3#maps) type. It looks like the map detection logic resides in the C++ code and that knowledge is not included in the JavaScript `CodeGeneratorResponse` from compiler/plugin_pb.js. 

**Describe the solution you'd like**

A boolean attribute or method `isMap` on the FieldDescriptor similar to `hasProto3Optional()`

**Comment by dibenede** [comment]
What FieldDescriptor type are you referring to? We don't own that API.

**Comment by tatethurston** [comment]
@dibenede can you direct me to the owner of the contents of `google-protobuf/google/protobuf/compiler/plugin_pb.js` from `google-protobuf`?

**Comment by lukesandberg** [comment]
detecting whether or not a given field is a map is tricky, but possible in the current API

given

```
message Foo {
  map<string,string> m = 1;
}
```

You will see a `FieldDescriptorProto` for m that has `getLabel() === Label.REPEATED` and `getType() == Type.TYPE_MESSAGE`

then to see if it is a map or just a repeated field you need to resolve `getTypeName()` to the DescriptorProto for the message.  If the getMapEntry() method of that DescriptorProto returns `true` then the field is a map.

We cannot change this API to make it easier since the descriptor api is shared across all proto runtimes.
